[package]
name = "datenlord_s3"
version = "0.1.0"
authors = ["Nugine <nugine@foxmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/datenlord/datenlord_s3"
readme = "README.md"
description = "S3 service implementation for datenlord"
keywords = ["s3"]
categories = ["web"]

[dependencies]
